### ISSUE TITLE
Gem enforces ancient version of HTTPparty

### ISSUE THREAD

**Issue by dalyons** [customerio/customerio-ruby#38]
Guys,

The pinning of HTTParty introduced in: https://github.com/customerio/customerio-ruby/commit/95524356c8808944e503b851c36c6e41549c5121

is pretty uncool. HTTParty is a common lib used by lots of other gems, and forcing it to an old version which globally restricts your projects usage of httpparty across all gems. 

IMHO, 1.8.7 compatibility (which seems what this restriction was implemented for) is not worth it at all. 1.8.7 was EOL'd in 2012, and stopped receiving security updates in 2013. Those few people stuck on 1.8.7 would be best served with a tagged `1_8_7_stable` branch or some such.

https://www.ruby-lang.org/en/news/2011/10/06/plans-for-1-8-7/

**Comment by alisdair** [comment]
This dependency does suck, and I agree that old Rubies shouldn't need to be supported with future gem releases. Upgrading dependencies is scary though, especially when they don't care about semver.

I think the best solution is to remove the HTTParty dependency altogether. Wrapping net/http to provide the `self.class.{post,put,delete}` methods we need should be fairly easy to do. The hardest part is probably getting timeouts right.

If you want to take a run at it, I'd be happy to review & test the PR. Otherwise I'll give it a shot when I get the time.

**Comment by alisdair** [comment]
@dalyons We've now released a version of the gem which does not depend on HTTParty at all. We've tested this internally as much as possible. Please give it a try and let us know if you hit any problems: https://rubygems.org/gems/customerio/versions/1.0.0
